CATEGORICAL_FIELDS = [
    "type",
    "status",
    "disclosure_date",
    "cve_code",
    "details.splunk.severity",
    "details.splunk.published_date",
    "details.splunk.last_modified",
    "details.splunk.cwe",
    "details.splunk.affected_products",
    "details.splunk.fixed_versions",
    "details.splunk.cve_ids",
]

TEXT_FIELDS = [
    "type",
    "code",
    "cve_code",
    "title",
    "vuln_type",
    "details.splunk.advisory_id",
    "details.splunk.description",
    "details.splunk.solution",
    "details.splunk.mitigations",
    "details.splunk.severity_summary",
    "details.splunk.severity_detail",
    "details.splunk.affected_versions",
    "details.splunk.all_affected_versions",
    "details.splunk.affected_components",
    "details.splunk.bug_ids",
    "details.splunk.oss",
    "details.splunk.credit",
    "details.splunk.packages",
    "details.splunk.product_status",
    "details.splunk.reference_links",
]
